# Makefile for [source/Grid/GridMain/AMR]   

Grid += Grid_data.o \
		gr_setGcFillNLayers.o gr_setMasks_gen.o gr_makeMaskConsistent_gen.o \
		gr_estimateError.o

Grid += \
        gr_getBlkIterator.o \
        gr_releaseBlkIterator.o \
        gr_iterator.o
