# Makefile for flashUtilities

flashUtilities += ut_sysMemData.o \
	ut_sysMemInterface.o \
	ut_sysMemCData.o \
	ut_sysMemCInterface.o \
	ut_sysMemBGKernel.o \
	ut_sysMemProc.o \
	ut_sysMemMallinfo.o \
	ut_sysMemRusage.o \
	ut_sysMemAutoDetect.o \
	ut_sysMemSummaryStats.o
