SolidMechanics += sm_pk_data.o \
                  sm_pk_init.o \
                  sm_pk_finalize.o \
                  sm_pk_interface.o \
                  sm_pk_ReadHDF5.o \
                  sm_pk_apply.o \
                  sm_pk_apply_entireBody.o \
	          sm_pk_Flapping_BermanWang.o \
                  sm_pk_fixed.o \
                  sm_pk_Whirl.o \
                  sm_pk_fixed_dof.o \
                  sm_pk_harmonic_dof.o \
                  sm_pk_masterslave_rigid.o \
                  sm_pk_Shaker.o \
                  sm_pk_constvel_dof.o \
                  sm_pk_updatekinematics_rigid.o \
                  sm_pk_angvelconstraint_rigid.o
