IncompNS += IncompNS_data.o \
            ins_computeDtLocal.o\
            ins_advance.o\
            ins_fluxes.o ins_rhs.o\
            ins_velgradtensor.o \
            ins_velomg2center.o \
            ins_vt.o \
            ins_vt_WALE.o \
            ins_interface.o \
            ins_setInterpValsGcell.o \
            ins_computeQinout.o \
            ins_rescaleVelout.o \
            ins_convectVelout.o \
            ins_ab2rk3_VD.o\
            ins_advance_VD.o\
            ins_rhs_VD.o

#dependencies below:
#ins_ab2rk3.o : ins_interface.o
#ins_vt.o  : ins_interface.o
#ins_velgradtensor.o  : ins_interface.o
