
Logfile += Logfile_stamp.o Logfile_init.o \
	Logfile_open.o \
	Logfile_interface.o \
	Logfile_writeSummary.o \
	Logfile_break.o \
	Logfile_stampMessage.o \
	Logfile_stampVarMask.o \
	Logfile_close.o \
	Logfile_create.o \
	Logfile_getDateTimeStr.o \
	Logfile_finalize.o





