RuntimeParameters += RuntimeParameters_init.o \
	RuntimeParameters_getNum.o \
	RuntimeParameters_getPrev.o \
	RuntimeParameters_read.o \
	RuntimeParameters_get.o \
	RuntimeParameters_getAll.o \
	RuntimeParameters_getNumIgn.o \
	RuntimeParameters_set.o \
	RuntimeParameters_setPrev.o \
	RuntimeParameters_add.o \
	RuntimeParameters_mapStrToInt.o \
	RuntimeParameters_finalize.o \
	RuntimeParameters_stampIgnored.o \
	RuntimeParameters_bcast.o RuntimeParameters_interface.o




