Flame += Flame_laminarSpeed.o fl_fsLaminarInterface.o \
         fl_fsLaminarFlameSpeedBlock.o fl_fsUnburnDensBlock.o \
         fl_fsLaminarInit.o fl_fsLaminarFinalize.o \
         fl_fsConeData.o fl_fsConeInterp.o fl_fsUnburnDens.o
