#	Makefile for multipole Poisson solver

#	Additional files

Grid += gr_isoMpoleInit.o gr_isoFindMassCenter.o gr_isoMpoleMoments.o \
           gr_isoZoneMoments.o gr_isoMpolePotential.o gr_isoMpoleData.o\
           gr_isoZonePotential.o gr_isoImageBdry.o gr_isoImageMass.o\
           gr_isoSumLocal.o
