SolidMechanics += sm_GenAlpha_data.o \
                  sm_ga_initdamp.o \
                  sm_ga_compute_qddn0.o \
                  sm_GenAlpha_readCheckpoint.o \
                  sm_ga_modstiff_fluid.o 
