SolidMechanics += sm_ioReadSolid.o \
                  sm_iointerface.o \
                  sm_io_checkHdfErr.o \
                  sm_ioWriteSnapshot.o \
                  sm_ioRead_rigid.o \
                  sm_ioRead_3DFlexible.o \
                  sm_ioRead_rbc.o \
		  sm_ioWrite_rbc.o \
                  sm_ioInit.o \
                  sm_ioInit_3DFlexible.o \
                  sm_ioInit_rigid.o \
                  sm_ioInit_rbc.o \
                  sm_ioWriteStates.o \
                  sm_ioWriteStates_3DFlexible.o \
                  sm_ioWriteStates_rigid.o \
                  sm_ioWriteStates_rbc.o \
		  sm_io_rbcinit.o \
                  sm_xdmfwrite.o \
                  sm_iouttotecplot.o \
		  outtoParaview.o \
                  sm_ioWriteParticles.o \
		  sm_rbc_CalcParms.o \
                  sm_uvTecplot.o 
