# Makefile for [source/Grid/GridBoundaryConditions]
Grid += gr_bcData.o gr_bcData.o gr_bcGetRegion.o gr_bcPutRegion.o  gr_extendedGetCellCoords.o

Grid += gr_bcMapBcType.o gr_hgMapBcType.o gr_mgMapBcType.o gr_bicgMapBcType.o

Grid += gr_bcApplyToOneFaceAllGds.o
