Grid += gr_pfftData.o gr_pfftNodeFnPrototypes.o gr_pfftNodeObject.o \
	gr_pfftListObject.o gr_pfftFnArgSendToPG.o gr_pfftFnArgRecvFromFG.o \
	gr_pfftFnArgRecvFromPG.o gr_pfftFnArgSendToFG.o \
	gr_pfftFnArgMsgDelivered.o gr_pfftFnArgCopyGridToBuf.o \
	gr_pfftFnArgCopyBufToGrid.o gr_pfftFnArgCopyPencilToBuf.o \
	gr_pfftFnArgCopyBufToPencil.o gr_pfftMapToInput.o \
	gr_pfftMapFromOutput.o gr_pfftInitMapData.o \
	gr_pfftFreeMap.o gr_pfftCreateNode.o gr_pfftCreateSendNode.o \
	gr_pfftCommunicateNodeMetaData.o gr_pfftGenMap.o gr_pfftReconfigData.o
gr_pfftListObject.o : gr_pfftNodeObject.o
