SolidMechanics += sm_surf_interface.o \
                  sm_surf_CountParticles_wsIEN.o \
                  sm_surf_MapParticles.o \
                  sm_surf_repoParticlesBC.o \
                  sm_surf_assembleFluidForce.o \
                  sm_surf_assembleFluidForce_toPoint.o \
                  sm_surf_assembleFluidForce_rigid.o \
                  sm_surf_currentFluidForce.o \
                  sm_surf_currentFluidForce_3DFlex.o \
                  sm_surf_currentFluidForce_rigid.o
