SolidMechanics += SolidMechanics.o \
                  SolidMechanics_init.o \
                  SolidMechanics_finalize.o \
                  SolidMechanics_computeDt.o \
                  SolidMechanics_interface.o

SolidMechanics.o: SolidMechanics_interface.o 
