#	Makefile for the local API (equation of state module)

Eos += eos_localInterface.o eos_idealGamma.o eos_idealGamma3T.o eos_mgamma.o eos_mtemp.o\
	eos_helmholtz.o eos_tabulated.o eos_tabIonmix.o\
	eos_initGamma.o eos_initMgamma.o eos_initHelmholtz.o\
	eos_initMtemp.o eos_initTabulated.o eos_tabFinalize.o\
	eos_initNuclear.o eos_nuclear.o

