# Makefile for flashUtilities

flashUtilities += removeNullChar.o \
                  current_date_time.o \
		  concatStringWithInt.o \
                  ut_generalInterface.o \
                  ut_getFreeFileUnit.o \
                  ut_printMatrix.o \
                  ut_constRealZeroFn1.o

