Grid +=  gr_pfftReconfigData.o gr_pfftGenMap.o \
         gr_pfftGenMapHelper.o gr_pfftBufferTransfer.o \
	 gr_pfftCopyToSendMap.o \
	 gr_pfftHandleJaxisFragments.o gr_pfftPrintCommBuffers.o \
         gr_pfftHandleKaxisFragments.o gr_pfftGroupUsableProcesses.o \
	 gr_pfftMapToInput.o gr_pfftMapFromOutput.o gr_pfftFreeMap.o
