#	Makefile for gravity module
Gravity += grv_bhInterface.o Gravity_data.o \
          grv_elintF.o grv_intCoef1P2I.o grv_intSimpson.o \
          grv_readExtrnPotential.o grv_accExtrnPotRow.o \
          grv_accExtrnPotPoint.o grv_bhGenEwaldFieldLevelV42.o \
          grv_bhGenEwaldField.o grv_bhGenEwaldFieldLevel.o \
          grv_bhInterface.o grv_bhAccShort.o \
          grv_bhAccLong1P2I.o grv_bhAccLong2P1I.o \
          grv_bhAccLong3P.o

