Simulation += Simulation_data.o               \
              sim_setMaxRelativeAccuracies.o  \
              sim_setx3PolynomialCoeffs.o     \
              sim_setx3PolynomialExactRoots.o \
              sim_x3PolynomialsRootsTest.o
