#	Makefile for the NEI sub-module
# Note: The version of nei in the directory IonizeMain/Eqi is provided for histoical purposes.
#       It will probably not work as is with an uncustomized IonizeMain/Ionize.F90.

Ionize +=  nei.o
