Grid +=  fftpack.o gr_pfftSetupDim.o \
         gr_pfftDcftForward.o gr_pfftDcftInverse.o gr_pfftIntersperse.o \
         gr_pfftDisperse.o gr_pfftLocalTranspose.o gr_pfftTranspose.o \
         gr_pfftInitMetaData.o \
         gr_pfftGetLocalLimits.o gr_pfftWave.o \
         gr_pfftDerivs.o \
	 gr_pfftGetLocalLimitsAnytime.o gr_pfftData.o \
	 gr_pfftSpecifyTransform.o

#gr_pfftReconfigData.o : gr_pfftListObject.o
