#	Makefile for gravity module
Gravity = Gravity_init.o Gravity_finalize.o Gravity_computeDt.o \
          Gravity_accelOneRow.o \
          Gravity_potential.o \
          Gravity_interface.o \
          Gravity_accelOneBlock.o 

#	for poisson gravity unitTest:

Gravity += Gravity_unitTest.o

