# Makefile for flashUtilities

flashUtilities += nameValueLL_data.o\
	nameValueLL_get.o \
	nameValueLL_getAll.o \
	nameValueLL_set.o \
	nameValueLL_getNum.o \
	makeLowercase.o \
	nameValueLL_bcast.o \
	findWords.o \
	nameSyntaxError.o \
	nameValueLL_rules.o \
	nameValueLL_logRules.o 
