#	Makefile for unit RadTrans (API level)
RadTrans = RadTrans.o \
	   RadTrans_init.o \
	   RadTrans_interface.o \
	   RadTrans_getDbgContext.o \
	   RadTrans_planckInt.o \
	   RadTrans_mgdGetBound.o \
	   RadTrans_mgdSetBound.o \
	   RadTrans_computeDt.o \
	   RadTrans_mgdEFromT.o \
	   RadTrans_sumEnergy.o \
	   RadTrans_mgdSetEnergy.o \
	   RadTrans_mgdSetBc.o \
	   RadTrans_computeFluxLimiter.o \
	   RadTrans_finalize.o
