# Makefile for source/physics/sourceTerms/Burn/BurnMain/nuclearBurn

Burn += Burn_data.o Burn_dataEOS.o bn_interface.o bn_burner.o \
	bn_dataNetworkSize.o bnNetwork_interface.o bn_finalizeNetwork.o \
	bn_azbar.o bn_ecapnuc.o bn_ifermi12.o bn_mazurek.o bn_mcord.o bn_screen4.o bn_sneutx.o

Burn_data.o : bn_dataNetworkSize.o
