SolidMechanics += element_shape_functions.o \
                  el05_mass.o \
                  el12_mass.o \
                  el15_mass.o \
                  el05_stiff_biot.o \
                  el05_stiff_kirch.o \
                  el12_stiff_biot.o \
                  el12_stiff_kirch.o \
                  el05_IntForce_biot.o \
                  el05_IntForce_kirch.o \
                  el12_IntForce_biot.o \
                  el12_IntForce_kirch.o \
                  sm_3DFlexible_getElement_EvalMax.o \
                  el10_lengths.o \
                  sm_el02_countParticles.o \
                  sm_el10_countParticles.o \
                  sm_el02_mapParticles.o \
                  sm_el10_mapParticles.o \
                  sm_el10_FluidForce.o \
                  sm_el10_ga_stiff.o \
	 	  sm_el02_FluidForce.o \
                  sm_el12_COM.o \
                  sm_el15_NBvars.o

el05_mass.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el12_mass.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el05_stiff_biot.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el05_stiff_kirch.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el12_stiff_biot.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el12_stiff_kirch.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el05_IntForce_biot.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el05_IntForce_kirch.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el12_IntForce_biot.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el12_IntForce_kirch.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
el10_lengths.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
sm_el10_FluidForces.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
sm_el12_COM.o : sm_quadrature.o sm_element_interface.o sm_Misc_interface.o 
