#	Makefile for TreeRay module
TreeRay = TreeRay_init.o TreeRay_finalize.o \
          TreeRay_interface.o \
          TreeRay_bhAccBotNode.o \
          TreeRay_bhAccNode.o \
          TreeRay_bhBTInit.o \
          TreeRay_bhCheckAccuracy.o \
          TreeRay_bhFillBotNode.o \
          TreeRay_bhFinalizeBlock.o \
          TreeRay_bhFinalizeIter.o \
          TreeRay_bhGetNodeStruct.o \
          TreeRay_bhInitFieldVar.o \
          TreeRay_bhMAC.o \
          TreeRay_bhNodeContrib.o \
          TreeRay_bhNormalizeNode.o \
          TreeRay_bhPartErr.o \
          TreeRay_bhPostprocNode.o \
          TreeRay_bhSelfContrib.o \
          TreeRay_bhStartBlock.o \
          TreeRay_bhTreeWalkEnd.o \
          TreeRay_potentialListOfBlocks.o


