Flame += Flame_interface.o  Flame_init.o Flame_finalize.o \
         Flame_computeAbarZbar.o \
         Flame_step.o Flame_getWidth.o Flame_getProfile.o \
	 Flame_laminarSpeed.o \
	 Flame_rhJump.o Flame_rhJumpReactive.o
