#	Makefile for gravity module
Gravity = Gravity_init.o Gravity_finalize.o Gravity_computeDt.o \
          Gravity_accelListOfBlocks.o Gravity_accelOneRow.o \
          Gravity_accelAtCoords.o \
          Gravity_potentialListOfBlocks.o \
          Gravity_interface.o \
          Gravity_accelOneBlock.o \
          Gravity_bhAccBotNode.o \
          Gravity_bhAccNode.o \
          Gravity_bhBTInit.o \
          Gravity_bhCheckAccuracy.o \
          Gravity_bhEwaldPot.o \
          Gravity_bhEwaldAcc.o \
          Gravity_bhEwaldPotV42.o \
          Gravity_bhEwaldAccV42.o \
          Gravity_bhFillBotNode.o \
          Gravity_bhFinalizeBlock.o \
          Gravity_bhFinalizeIter.o \
          Gravity_bhGetNodeStruct.o \
          Gravity_bhInitFieldVar.o \
          Gravity_bhMAC.o \
          Gravity_bhNodeContrib.o \
          Gravity_bhNormalizeNode.o \
          Gravity_bhPartErr.o \
          Gravity_bhPostprocNode.o \
          Gravity_bhSelfContrib.o \
          Gravity_bhStartBlock.o \
          Gravity_bhTreeWalkEnd.o


