#	Makefile for the FLASH code (equation of state module)

Eos = Eos_wrapped.o Eos.o Eos_init.o Eos_finalize.o Eos_guardCells.o Eos_getParameters.o Eos_interface.o Eos_getData.o Eos_putData.o Eos_getAbarZbar.o \
	Eos_nucOneZone.o Eos_nucDetectBounce.o Eos_nucInterface.o \
	Eos_getTempData.o Eos_logDiagnostics.o
