#	Makefile for the OpticalDepth subunit of treeray module
TreeRay += tr_odInit.o tr_odFinalize.o tr_odData.o \
           tr_odNodeContrib.o \
           tr_odSelfContrib.o calc_shield.o \
           tr_odStartBlock.o TreeRay_bhFinalizeBlock.o \
           tr_odInitFieldVar.o

