Roots += Roots_finalize.o         \
         Roots_init.o             \
         Roots_interface.o        \
         Roots_x2Polynomial.o     \
         Roots_x3Polynomial.o     \
         Roots_x4Polynomial.o
