#	Makefile for Gravity/GravityMain/Poisson/tree:  tree Poisson solver

#	Additional files

Grid += gr_bhData.o \
           gr_bhBuildTree.o \
           gr_bhBuildTreeBlock.o \
           gr_bhExchangeTrees.o \
           gr_bhDestroyTree.o \
           gr_bhGetTreeSize.o \
           gr_bhTreeWalk.o \
           gr_bhTreeWalkBlock.o \
           gr_bhTreeWalkBlockUnified.o \
           gr_bhTreeWalkBlockPQ.o \
           gr_bhTreeWalkPoint.o \
           gr_bhGetTreePos.o \
           gr_bhGetBlockWorkload.o \
           gr_bhLeafContrib.o \
           gr_bhLocalInterface.o \
           gr_bhPeriodicDr.o \
           gr_bhInit.o \
           gr_bhLeafContrib.o \
           gr_bhParentContrib.o \
           gr_bhComParentTree.o \
           gr_bhComBlkProperties.o \
           gr_bhMAC.o \
           gr_bhPartErr.o \
           gr_bhFillBotNode.o \
           gr_bhAccBotNode.o \
           gr_bhNormalizeNode.o \
           gr_bhPostprocNode.o \
           gr_bhAccNode.o \
           gr_bhNodeContrib.o \
           gr_bhBotNodeContrib.o \
           gr_bhBTInit.o \
           gr_bhSelfContrib.o \
           gr_bhInitFieldVar.o \
           gr_bhStartBlock.o \
           gr_bhFinalize.o \
           gr_bhFinalizeBlock.o \
           gr_bhFinalizeIter.o \
           gr_bhCalcBlockTreePos.o \
           gr_bhPQInsert.o \
           gr_bhPQPull.o \
           gr_bhGetTreeNodeSize.o \
           gr_bhCheckAccuracy.o





