
IO += IO_init.o \
	IO_output.o \
	IO_setScalar.o \
	IO_readCheckpoint.o \
	IO_getScalar.o \
	IO_outputInitial.o \
	IO_outputFinal.o \
	IO_sendOutputData.o \
	IO_getPrevScalar.o \
	IO_writeIntegralQuantities.o \
	IO_writeParticles.o \
	IO_readParticles.o \
	IO_writeCheckpoint.o \
	IO_updateScalars.o \
	IO_writePlotfile.o \
	IO_finalize.o \
	IO_writeUserArray.o \
	IO_readUserArray.o \
	IO_initRPsFromCheckpoint.o \
        IO_interface.o \
	IO_checkForPlot.o \
        IO_startProtonWrite.o \
        IO_startRayWrite.o \
	IO_writeProtons.o \
	IO_writeRays.o \
        IO_endProtonWrite.o \
        IO_endRayWrite.o

