IncompNS += IncompNS_interface.o \
	    IncompNS.o IncompNS_init.o \
	    IncompNS_sendOutputData.o \
            IncompNS_computeDt.o \
	    IncompNS_finalize.o \
            IncompNS_velomg2center.o \
            IncompNS_stats.o \
            IncompNS_statsIOExport.o


