Grid += $(multigrid)

multigrid = gr_mgData.o gr_mgInit.o gr_mgInitSlv.o gr_mgInitSrc.o gr_mgNorm.o gr_mgBndry.o \
            gr_mgGuardcell.o gr_mgCycle.o gr_mgZero.o gr_mgCopy.o gr_mgCorrect.o \
            gr_mgProlong.o gr_mgRestrict.o gr_mgSolve.o 
