Hydro += hy_uhd_HLLD.o\
	hy_uhd_getElectricFields.o\
	hy_uhd_getFluxDeriv.o\
	hy_uhd_staggeredDivb.o\
	hy_uhd_addResistiveFluxes.o\
	hy_uhd_addBiermannBatteryTerms.o\
	hy_uhd_biermannSource.o\
	hy_uhd_addOhmicHeating.o

