IO += io_h5_xfer_mesh_dataset.o io_h5_xfer_packed_mesh_dataset.o io_h5_read_file_format.o

io_h5_xfer_mesh_dataset.o: io_h5_xfer_mesh_dataset.h hdf5_flash.h constants.h \
	Flash.h io_flash.h
io_h5_xfer_packed_mesh_dataset.o: io_h5_xfer_packed_mesh_dataset.h constants.h \
	Flash.h io_repack_data.h io_use_grid_mpi_types.h io_flash.h \
	io_h5_xfer_wrapper.h io_h5_type.h
