SolidMechanics += sm_integdata.o \
		  sm_integinterface.o \
		  sm_integ_advance.o \
                  sm_integ_adv1dt.o \
                  sm_integ_checkconverg.o \
                  sm_integ_writeCheckpoint.o \
		  sm_PredCorr_init.o \
                  sm_PredCorr_advance.o \
                  sm_PredCorr_checkconverg.o \
                  sm_PredCorr_writeCheckpoint.o \
                  sm_Verlet_init.o \
                  sm_Verlet_advance.o \
                  sm_Verlet_writeCheckpoint.o \
                  sm_EstDT_3DFlexible.o \
                  sm_EstDT_rigid.o \
                  sm_EstDT_rbc.o \
                  sm_GenAlpha_init.o \
                  sm_GenAlpha_advance.o \
                  sm_GenAlpha_checkconverg.o \
                  sm_GenAlpha_writeCheckpoint.o \
                  sm_ga_isPredictor.o \
                  sm_ga_isCorrector.o \
                  sm_pc_isPredictor.o \
                  sm_pc_isCorrector.o 
