SolidMechanics += sm_PredCorr_data.o \
                  sm_predcorrInteg.o \
                  sm_pcintegEuler.o \
                  sm_pcinteg_AB2.o \
                  sm_pcinteg_AB3.o \
                  sm_pcinteg_AB4.o \
                  sm_pc_initmass.o \
                  sm_pc_compute_qddn.o \
                  sm_pc_initdamp.o \
                  sm_PredCorr_readCheckpoint.o

sm_pc_initmass.o : sm_Misc_interface.o sm_c2fortran_dgssv.o 
sm_pc_compute_qddn.o : sm_Misc_interface.o sm_c2fortran_dgssv.o
