Simulation += Simulation_data.o               \
              sim_setMaxRelativeAccuracies.o  \
              sim_setx4PolynomialCoeffs.o     \
              sim_setx4PolynomialExactRoots.o \
              sim_x4PolynomialsRootsTest.o
