# Makefile for the basic stub level of Particles [/source/Particles]

Particles +=  \
	Particles_advance.o \
	Particles_computeDt.o \
	Particles_dump.o  \
	Particles_finalize.o \
	Particles_getGlobalNum.o \
	Particles_getLocalNum.o \
	Particles_init.o \
	Particles_initPositions.o \
	Particles_putLocalNum.o \
	Particles_updateAttributes.o \
	Particles_sendOutputData.o \
	Particles_updateRefinement.o\
	Particles_unitTest.o \
	Particles_mapFromMesh.o \
	Particles_mapToMeshOneBlk.o \
	Particles_updateGridVar.o \
	Particles_interface.o \
	Particles_getCountPerBlk.o \
	Particles_accumCount.o \
	Particles_initData.o \
	Particles_initForces.o \
	Particles_manageLost.o \
	Particles_addNew.o \
	Particles_clean.o 	
