# Makefile for a time andvancement Test for passive Particles
# [source/Simulation/SimulationMain/unitTest/particlesAdvance/HomologousPassive]

Simulation += Simulation_data.o sim_interface.o sim_ptAnaGetVelComponent.o \
	sim_grAnaGetVelComponent.o \
	sim_getComputedError.o
Simulation_init.o : Simulation_data.o
Simulation_initBlock.o : Simulation_data.o
