#	Makefile for the sourceTerm Diffuse (API level)

Diffuse = Diffuse_init.o Diffuse.o Diffuse_visc.o Diffuse_species.o Diffuse_therm.o \
          Diffuse_computeDt.o Diffuse_finalize.o Diffuse_interface.o \
	  Diffuse_advance1D.o Diffuse_solveScalar.o \
	  Diffuse_solveCoupledScalar.o \
	  Diffuse_fluxLimiter.o Diffuse_computeFluxLimiter.o \
	  Diffuse_setContextInfo.o
