Grid += gr_hgBndry.o gr_hgData.o gr_hgInitSource.o \
        gr_hgLevelAdd.o gr_hgLevelAddScalar.o gr_hgLevelMultiplyScalar.o  \
        gr_hgLevelZero.o gr_hgNorm.o Grid_solvePoisson.o \
        gr_hgProlongBndries.o gr_hgResidual.o gr_hgRestrict.o \
        gr_hgSetZeroBoundary.o gr_hgSetExtBoundary.o gr_hgSolve.o \
        gr_hgSolveLevel.o gr_hgGuardCell.o gr_hgRestoreNodeTypes.o \
        gr_hgSetMaxLevel.o gr_hgRecordNodeTypeState.o gr_hgFinalize.o \
	gr_hgPoissonSolve1D.o gr_hgPoissonSolve2D.o gr_hgPoissonSolve3D.o \
        gr_hgPoissonSolveBlock.o
#         amr_get_new_nodetypes.o amr_mg_common.o amr_mg_init.o \
#         amr_mg_morton_process.o amr_mg_prolong.o amr_mg_restrict.o \
#         mpi_amr_store_comm_info_mg.o gr_hgSetMaxLevel.o
