SolidMechanics +=   sm_assemble_interface.o \
                    sm_assemble_mass.o \
                    sm_assemble_stiff.o \
                    sm_assemble_IntForce.o \
                    sm_assemble_IntForce_3DFlexible.o \
                    sm_assemble_stiff_3DFlexible.o \
                    sm_assemble_mass_3DFlexible.o \
                    sm_assemble_IntForce_rigid.o \
                    sm_assemble_stiff_rigid.o \
                    sm_assemble_mass_rigid.o \
                    sm_assemble_IntForce_rbc.o \
                    sm_assemble_stiff_rbc.o \
                    sm_assemble_mass_rbc.o \
                    sm_assemble_ExtForce.o \
                    sm_assemble_ExtForce_3DFlexible.o \
                    sm_assemble_ExtForce_rigid.o \
                    sm_assemble_ExtForce_rbc.o \
                    sm_assemble_COM.o \
                    sm_assemble_COM_3DFlexible.o \
                    sm_assemble_COM_rigid.o \
                    sm_assemble_COM_rbc.o \
                    sm_assemble_FluidVolIntegrals.o
