# Makefile for FLASH code (8Wave MHD unit)
# physics/Hydro/HydroMain/split/MHD_8Wave/

Hydro += Hydro_data.o\
	hy_8wv_fluxes.o \
	hy_8wv_interpolate.o \
	hy_8wv_sources.o \
	hy_8wv_setTimestep.o \
	hy_8wv_sweep.o \
	hy_8wv_addViscousFluxes.o \
	hy_8wv_addResistiveFluxes.o \
	hy_8wv_addThermalFluxes.o \
	hy_8wv_addHallFluxes.o\
	hy_8wv_interface.o \
	hy_8wv_divb.o
