#	Makefile for Grid/GridSolvers/Multipole:  multipole Poisson solver

#	Additional files

Grid += gr_mpoleCenterOfMass.o gr_mpoleLocalSum.o gr_mpoleData.o \
           gr_mpoleMoments.o gr_mpolePotential.o  \
           gr_mpoleSphABTerms.o gr_mpoleSphBlkPotential.o \
           gr_mpoleDumpMoments.o \
           gr_zoneMoments.o gr_zonePotential.o gr_mpoleEvalBin.o




