# Makefile for initial setup of hydrostatic spherical galaxy cluster

Simulation += Simulation_data.o

# Additional dependencies

Simulation_init.o: Simulation_data.o
Simulation_initBlock.o :  Simulation_data.o 
