# Makefile for [source/Grid/GridMain/AMR/paramesh]   

Grid += gr_updateData.o gr_createDomain.o gr_recreateDomain.o \
        gr_createBlock.o gr_expandDomain.o \
	gr_primitiveToConserve.o \
	gr_conserveToPrimitive.o Paramesh_init.o   \
        Paramesh_finalize.o  gr_initParameshArrays.o \
	gr_restrictTree.o \
	gr_markVarThreshold.o gr_markInRadius.o gr_markWithRadius.o \
        gr_markInRectangle.o gr_markEllipsoid.o \
        gr_updateRefinement.o gr_findWhichChild.o gr_getBlkHandle.o \
	gr_findWhichChildren.o \
	gr_unmarkRefineByLogRadius.o gr_markDerefineByLogRadius.o gr_markDerefineByTime.o gr_enforceMaxRefine.o \
	gr_setMaxRefineByTime.o gr_specificData.o gr_initSpecific.o \
	gr_parameshInterface.o gr_pmGetListOfBlocks.o gr_findBlock.o

