#  Makefile for cosmology module.

Cosmology += Cosmology_init.o \
	     Cosmology_interface.o \
	     Cosmology_finalize.o \
	     Cosmology_redshiftToTime.o \
	     Cosmology_getRedshift.o \
	     Cosmology_getOldRedshift.o \
             Cosmology_sendOutputData.o \
             Cosmology_computeDt.o \
             Cosmology_getParams.o \
             Cosmology_redshiftHydro.o \
	     Cosmology_solveFriedmannEqn.o\
	     Cosmology_cdmPowerSpectrum.o\
	     Cosmology_massToLength.o
