#	Makefile for the nuclear burning sub-module
# [/source/physics/sourceTerms/Burn/]

Burn += Burn.o Burn_computeDt.o Burn_init.o Burn_finalize.o Burn_interface.o \
        Burn_computeAbarZbar.o \
	Burn_guardCellMaskHook.o \
	Burn_nseAtDens.o Burn_nseAtPres.o 

