#	Makefile for 1D piecewise-parabolic method (PPM) module

Hydro += hydro_1d.o \
         grdvel.o \
         avisco.o \
         intrfc.o \
         rieman.o \
         riemann_hlle.o \
         states.o \
         coeff.o \
         detect.o \
         flaten.o \
         interp.o hy_interpNoLim.o \
         cma_flatten.o \
         monot.o hy_nomonot.o \
	 interp_char.o
