# Makefile for [source/Grid/GridMain]
Grid +=  Grid_getSingleCellVol.o \
	gr_checkDataType.o  gr_initGeometry.o gr_getCellVol.o gr_getCellFaceArea.o \
	Grid_renormAbundance.o Grid_limitAbundance.o Grid_renormMassScalars.o \
	gr_extendedGetDeltas.o gr_setDataStructInfo.o gr_findBlock.o gr_findMean.o \
	gr_GCAllocScratch.o gr_GCScratchData.o gr_GCReleaseScratch.o \
	gr_GCTransferOneBlk.o
