#	Makefile for sourceTerm PrimordialChemistry (API Level)

PrimordialChemistry += PrimordialChemistry_init.o PrimordialChemistry_interface.o PrimordialChemistry.o PrimordialChemistry_finalize.o PrimordialChemistry_computeDt.o 