Simulation += Simulation_data.o          \
              sim_analyzeDetectorsData.o \
              sim_doAnalysis.o           \
              sim_doProtonImaging.o      \
              sim_initBlock3DRec.o       \
              sim_printBlockData.o       \
              sim_printResults.o
