Pipeline += Pipeline_finalize.o             \
	    Pipeline_globalCheckStatus.o    \
	    Pipeline_globalCheckStructure.o \
	    Pipeline_init.o                 \
            Pipeline_interface.o            \
            Pipeline_localActivate.o        \
            Pipeline_localCreate.o          \
            Pipeline_localDeactivate.o      \
            Pipeline_localDestroy.o         \
            Pipeline_localFlush.o           \
            Pipeline_localGetItems.o        \
            Pipeline_localPrintSnapshot.o   \
            Pipeline_localProgress.o        \
            Pipeline_localSendItem.o
