Simulation += Simulation_data.o               \
              sim_setMaxRelativeAccuracies.o  \
              sim_setx2PolynomialCoeffs.o     \
              sim_setx2PolynomialExactRoots.o \
              sim_x2PolynomialsRootsTest.o
