#	Makefile for the IonizeMain

Ionize +=  Ionize_data.o \
	   ion_intCoeff.o \
           ion_readTable.o \
           ion_wint.o \
           ion_mcord.o \
           ion_selectElements.o \
	   ion_interface.o
