#	Makefile for the Diffuse/localAPI

Diffuse += diff_saInit.o diff_fbInit.o diff_advanceTherm.o diff_saFinalize.o diff_computeFluxes.o \
           diff_computeAX.o diff_computeblkAMat.o diff_computeILU.o diff_applyPC.o \
           diff_interface.o
