Multispecies += Multispecies_setProperty.o \
	Multispecies_getProperty.o \
	Multispecies_getPropertyVector.o \
	Multispecies_getAvg.o \
	Multispecies_getSum.o \
	Multispecies_getSumInv.o \
	Multispecies_getSumFrac.o \
	Multispecies_getSumSqr.o \
	Multispecies_init.o \
	Multispecies_list.o \
	Multispecies_finalize.o \
	Multispecies_unitTest.o Multispecies_interface.o







