ThomsonScattering += thsc_beamsCheck2DCyl3D.o           \
                 thsc_beamsCheck3DRec.o             \
                 thsc_beamsCheck.o                  \
                 thsc_beamsInfo3DRec.o              \
                 thsc_beamsInfo.o                   \
                 thsc_closeDetectorFiles.o          \
                 thsc_computeBeamPower.o            \
                 thsc_detectorsCheck3DRec.o         \
                 thsc_detectorsCheck.o              \
                 thsc_detectorsInfo3DRec.o          \
                 thsc_detectorsInfo.o               \
                 thsc_flushDetectorData2Disk.o     \
                 thsc_initializeBeams.o             \
                 thsc_initializeDetectors.o         \
                 thsc_constInterface.o              \
                 thsc_interface.o                   \
                 thsc_openDetectorFiles.o           \
                 thsc_printPulsesData.o             \
                 thsc_printBeamsData.o              \
                 thsc_printBlockVariable.o          \
                 thsc_printDetectorsData.o          \
                 thsc_printMainData.o               \
                 thsc_recordRayOnDetector.o        \
                 thsc_rescaleBeamPowers.o           \
                 thsc_setupBeams.o                  \
                 thsc_setupPulses.o                 \
                 thsc_setupDetectors.o              \
                 thsc_setupDetectedRays.o          \
                 thsc_rayLoop.o \
                 thsc_integrate.o \
                 thsc_prune1.o \
                 thsc_prune2.o \
                 thsc_rayGetPowerIn.o \
                 thsc_traceToDetector.o \
                 thsc_write2DetectorFile.o \
                 thsc_write2SpectrumFile.o

# ProtonImaging += thsc_beamsCheck2DCyl3D.o           \
#                  thsc_beamsCheck3DRec.o             \
#                  thsc_beamsCheck.o                  \
#                  thsc_beamsInfo3DRec.o              \
#                  thsc_beamsInfo.o                   \
#                  thsc_blockData3DRec.o              \
#                  thsc_calculateCellData.o           \
#                  thsc_capsuleGrainIndices2xyz.o     \
#                  thsc_capsuleNextGrainIndices.o     \
#                  thsc_capsuleTotalGrainCount.o      \
#                  thsc_closeDetectorFiles.o          \
#                  thsc_createProtons3DRec.o          \
#                  thsc_createProtons.o               \
#                  thsc_createProtonTags.o            \
#                  thsc_detectorsCheck3DRec.o         \
#                  thsc_detectorsCheck.o              \
#                  thsc_detectorsInfo3DRec.o          \
#                  thsc_detectorsInfo.o               \
#                  thsc_flushScreenProtons2Disk.o     \
#                  thsc_initializeBeams.o             \
#                  thsc_initializeDetectors.o         \
#                  thsc_interface.o                   \
#                  thsc_maxConfinement3DRec.o         \
#                  thsc_minConfinement3DRec.o         \
#                  thsc_openDetectorFiles.o           \
#                  thsc_parabolicPathLength3D.o       \
#                  thsc_printBeamsData.o              \
#                  thsc_printBlockVariable.o          \
#                  thsc_printDetectorsData.o          \
#                  thsc_printMainData.o               \
#                  thsc_printMatrix.o                 \
#                  thsc_printProtonsData.o            \
#                  thsc_protonsBlockIDInfo.o          \
#                  thsc_recordProtonOnScreen.o        \
#                  thsc_setupBeams.o                  \
#                  thsc_setupDetectors.o              \
#                  thsc_setupProtons.o                \
#                  thsc_setupScreenProtons.o          \
#                  thsc_time2FacesParabolicPath1D.o   \
#                  thsc_traceBlockProtons3DRec.o      \
#                  thsc_traceODEfunction3DRec.o       \
#                  thsc_traceProtons3DRec.o           \
#                  thsc_traceProtons.o                \
#                  thsc_updateProtons.o               \
#                  thsc_write2DetectorFile.o
