Interpolate += Interpolate_cubic1Dcoeffs.o    \
               Interpolate_cubic1DFd1d2.o     \
               Interpolate_cubic1DFd1.o       \
               Interpolate_cubic1DF.o         \
               Interpolate_cubic1DmonoDerv.o  \
               Interpolate_cubic2Dcoeffs.o    \
               Interpolate_cubic2DFd1d2.o     \
               Interpolate_cubic2DFd1.o       \
               Interpolate_cubic2DF.o         \
               Interpolate_cubic2DmonoDerv.o  \
               Interpolate_cubic3Dcoeffs.o    \
               Interpolate_cubic3DFd1d2.o     \
               Interpolate_cubic3DFd1.o       \
               Interpolate_cubic3DF.o         \
               Interpolate_cubic3DmonoDerv.o  \
               Interpolate_finalize.o         \
               Interpolate_init.o             \
               Interpolate_interface.o
