#define UT_SYSMEM_NONE -1
#define UT_SYSMEM_AUTO 0
#define UT_SYSMEM_PROC 1
#define UT_SYSMEM_RUSAGE 2
#define UT_SYSMEM_MALLINFO 4
#define UT_SYSMEM_BGKERNEL 8

#define UT_SYSMEM_ALL UT_SYSMEM_PROC + UT_SYSMEM_RUSAGE + \
  UT_SYSMEM_MALLINFO + UT_SYSMEM_BGKERNEL
