#  Makefile for the initialization section of the Particles module 
# [source/Particles/ParticlesInitialization]

Particles += pt_interface.o pt_initPositions.o pt_initPositionsLattice.o \
        pt_initPositionsWithDensity.o pt_initFinalize.o \
	pt_initLocal.o pt_mapStringParamToInt.o pt_mapFromMeshQuadratic.o \
	pt_mapFromMeshWeighted.o pt_assignWeights.o \
	pt_updateTypeDS.o pt_prepareEsti.o pt_advanceRK.o \
	pt_advanceEuler_passive.o pt_advanceMidpoint.o \
	pt_advanceEsti.o pt_advanceEuler_active.o \
	pt_advanceLeapfrog.o pt_advanceLeapfrog_cosmo.o \
	pt_advanceCharged.o pt_advanceCustom.o pt_findTagOffset.o 

Particles += pt_utFakeParticlesAdvance.o pt_utUpdateAnaPosns.o \
	pt_utAnaGetNewPosComponents.o pt_utComputeError.o 

Particles += pt_picInit.o pt_dpdInit.o pt_advanceDPD.o \
	pt_dpdNonBondedForces.o pt_dpdBondedForces.o pt_dpdSetIndices.o 