Pipeline += pl_interface.o               \
            pl_localPipelineSetup.o      \
            pl_localPostRecvMsg.o        \
            pl_localPostSendMsg.o        \
            pl_localSaveRecvItems.o      \
            pl_masterPipelineMap.o       \
            pl_printPipelineMap.o
