CCOMP = h5pcc 
LFLAGS = -o
CDEFINES = 

CFLAGS = -c -DNO_NCDF -DNO_HDF4 -DH5_USE_16_API

LIBS = 

EXENAME = sfocu
OBJS = main.o sfocu.o flash_reader.o namecmp.o flash_reader_hdf5.o flash_reader_chombo.o sameblock.o options.o

.SUFFIXES: .c .o
.c.o :
	$(CCOMP) $(CFLAGS) $(CDEFINES) $*.c

default: $(OBJS)
	$(CCOMP) $(OBJS) $(LIBS) $(LFLAGS) $(EXENAME)

clean:
	rm -f $(OBJS) $(EXENAME)
