SolidMechanics += sm_Misc_interface.o \
                  sm_quadrature.o \
                  compute_Jacobian3d.o \
                  det33.o \
                  DGEMV_sparse.o \
                  get_Nodal_UVW_qdn.o \
                  get_Nodal_UVW_qi.o \
                  get_Nodal_UVW_qn.o \
                  get_Nodal_XYZ.o \
                  sm_deallocateBody.o \
                  sm_c2fortran_dgssv.o \
                  get_Nodal_XYZ_ws.o \
                  get_Nodal_UVW_qi_ws.o \
                  get_Nodal_UVW_qn_ws.o \
                  sm_crossProd.o \
                  sm_crossProd_mat.o \
                  sm_get_numBodies.o \
                  sm_numrec.o 

sm_Misc_interface.o : SolidMechanics_data.o 
