#	Makefile for multigrid Poisson solver

Grid += Grid_solvePoisson.o poisson_mg_residual.o \
        poisson_mg_residual_leafs.o poisson_mg_relax.o poisson_mg_relax_ZEBRA.o \
        poisson_mg_solve.o gr_mpiMortonBndLeafOnly.o
